language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '7'
  - '6'
  - '4'
  - '8'
install: npm install
jobs:
  include:
    - stage: unit, integration and snapshot testing
      script: npm test
